hanghae99-Challenge-2-teams/NETicket

- src/main/java/com/example/neticket/event/controller/EventController.java
- src/main/java/com/example/neticket/event/dto/DetailEventResponseDto.java
- src/main/java/com/example/neticket/event/dto/EventResponseDto.java
- src/main/java/com/example/neticket/event/dto/ShowtimeResponseDto.java
- src/main/java/com/example/neticket/event/entity/Event.java
- src/main/java/com/example/neticket/event/repository/EventRepository.java
- src/main/java/com/example/neticket/event/service/EventService.java
> Dev <- Feature/gy #8 #10

- src/main/resources/templates/index.html
- src/main/resources/templates/login.html
> Feat : 메인페이지 index.html 추가

- src/main/java/com/example/neticket/event/service/EventService.java
- src/main/resources/templates/index.html
Fix: Pageable 값 8 -> 4 수정
HTML/CSS 수정 및 백엔드 pageable
> Design: mainpage HTML/CSS 구성완료

- src/main/resources/templates/login.html
> Fix : login.html 회원가입 버튼 오타 수정

- src/main/resources/templates/detail.html
- src/main/resources/templates/index.html
페이지 값 가져오기, 폰트 수정, 타이머 등록
Resolves: #6
> Feat: detail 페이지 값 가져오기

- src/main/java/com/example/neticket/connection/PageController.java
- src/main/java/com/example/neticket/reservation/controller/ReservationController.java
- src/main/java/com/example/neticket/reservation/service/ReservationService.java
- src/main/resources/templates/reservation.html
reservation.html
Resolved : #31
> Feat : 공연 상세페이지에서 예약하기 누르고 예약중 페이지 연결후 예약하기 기능구현 완료

- src/main/java/com/example/neticket/connection/PageController.java
- src/main/java/com/example/neticket/event/controller/EventController.java
- src/main/java/com/example/neticket/event/dto/DetailEventResponseDto.java
- src/main/java/com/example/neticket/event/dto/EventResponseDto.java
- src/main/java/com/example/neticket/event/entity/Event.java
- src/main/java/com/example/neticket/event/entity/TicketInfo.java
- src/main/java/com/example/neticket/event/service/TicketInfoService.java
- src/main/java/com/example/neticket/reservation/controller/ReservationController.java
- src/main/java/com/example/neticket/reservation/dto/ReservationRequestDto.java
- src/main/java/com/example/neticket/reservation/dto/ReservationResponseDto.java
- src/main/java/com/example/neticket/reservation/service/ReservationService.java
- src/main/java/com/example/neticket/user/controller/UserController.java
- src/main/java/com/example/neticket/user/service/UserService.java
- src/main/resources/templates/login.html
- src/main/resources/templates/reservation.html
- src/main/resources/templates/signup.html
ResponseEntity로 반환으로 수정, 기타코드 수정
Resolved : #15
> Reafactor : 백엔드 코드 리펙토링

- src/main/java/com/example/neticket/event/service/TicketInfoService.java
LocalDateTime에서 time 추가로 인해 공연 당일부터 예매 불가능 되게 수정
Related to:#15
> Fix: Scheduler 로직 수정

- build.gradle
- src/main/java/com/example/neticket/config/WebSecurityConfig.java
'com.mysql:mysql-connector-j' 추가
Resolved : #15
> fix : mysql의존성 추가

- src/main/java/com/example/neticket/event/entity/TicketInfo.java
- src/main/java/com/example/neticket/event/repository/TicketInfoRepository.java
- src/main/java/com/example/neticket/reservation/service/ReservationService.java
- src/main/resources/import.sql
fix : MySql RDS로 바꾸고 LockAcquisitionException 오류 해결
TicketInfo를 pessimistic lock으로 바꿔서 LockAcquisitionException 해결
> LockAcquisitionException 오류 해결

- src/main/java/com/example/neticket/connection/PageController.java
- src/main/java/com/example/neticket/reservation/controller/ReservationController.java
- src/main/java/com/example/neticket/reservation/repository/ReservationRepository.java
- src/main/java/com/example/neticket/user/controller/UserController.java
- src/main/java/com/example/neticket/user/service/UserService.java
마이페이지 만들기
페이지 컨트롤러 마이페이지 공연작성 페이지 추가
reservationcontroller에 @valid 추가
Resolves: #47
> Feat : 마이페이지 만들기

- src/main/java/com/example/neticket/config/S3Config.java
- src/main/java/com/example/neticket/event/controller/EventController.java
- src/main/java/com/example/neticket/event/dto/DetailEventResponseDto.java
- src/main/java/com/example/neticket/event/dto/EventRequestDto.java
- src/main/java/com/example/neticket/event/dto/EventResponseDto.java
- src/main/java/com/example/neticket/event/entity/Event.java
- src/main/java/com/example/neticket/event/entity/TicketInfo.java
- src/main/java/com/example/neticket/event/service/EventService.java
- src/main/java/com/example/neticket/reservation/controller/ReservationController.java
- src/main/java/com/example/neticket/reservation/service/ReservationService.java
- src/main/resources/import.sql
Event.java
EventController.java
EventService.java
관리자 공연추가 기능
Resolved : #48
> feat : 공연추가기능 구현 완료

- src/main/java/com/example/neticket/event/entity/Event.java
- src/main/java/com/example/neticket/event/entity/TicketInfo.java
- src/main/java/com/example/neticket/exception/ExceptionType.java
- src/main/java/com/example/neticket/exception/GlobalExceptionHandler.java
- src/main/java/com/example/neticket/reservation/controller/ReservationController.java
- src/main/java/com/example/neticket/reservation/entity/Reservation.java
- src/main/java/com/example/neticket/reservation/service/ReservationService.java
Feat: 예매취소 기능 추가
예매취소 기능 추가, 커스텀Exception 추가
Related: #55
> dev <- Feature/yujin

- src/main/java/com/example/neticket/event/controller/EventController.java
- src/main/java/com/example/neticket/event/service/EventService.java
- src/main/java/com/example/neticket/user/controller/UserController.java
- src/main/java/com/example/neticket/user/dto/LoginResponseDto.java
- src/main/java/com/example/neticket/user/service/UserService.java
- src/main/resources/import.sql
- src/main/resources/static/js/basic.js
- src/main/resources/templates/detail.html
- src/main/resources/templates/mypage.html
추후 완성도 높은 구현을 위해 임시 보류.
백엔드와 프론트 모두 주석 처리
마이페이지에서 이미지 삭제
> Refactor : 공연 삭제 기능 주석처리

- src/main/java/com/example/neticket/connection/PageController.java
- src/main/java/com/example/neticket/exception/GlobalExceptionHandler.java
- src/main/java/com/example/neticket/reservation/service/ReservationService.java
- src/main/resources/static/js/basic.js
- src/main/resources/templates/completed.html
- src/main/resources/templates/detail.html
- src/main/resources/templates/index.html
- src/main/resources/templates/mypage.html
- src/main/resources/templates/reservation.html
- src/main/resources/templates/signup.html
css오류 나는거 수정. 불필요한 코드 제거
Related to: #40, #15
> Refactor : 같이 코드 리뷰 후 수정

- src/test/java/com/example/neticket/event/service/EventServiceTest.java
EventServiceTest.java
Resolved : #50
> Test : 메인페이지, 상세페이지 TestCode

- src/main/java/com/example/neticket/event/dto/EventRequestDto.java
- src/main/java/com/example/neticket/reservation/dto/ReservationRequestDto.java
- src/main/java/com/example/neticket/reservation/dto/ReservationResponseDto.java
- src/main/java/com/example/neticket/user/dto/SignupRequestDto.java
RequestDto에 @NoArgsConstructor(access = AccessLevel.PROTECTED) 추가
> Fix : Type definition error 수정

- src/main/java/com/example/neticket/exception/ExceptionType.java
- src/main/java/com/example/neticket/reservation/controller/ReservationController.java
- src/main/java/com/example/neticket/reservation/repository/RedisRepository.java
- src/main/java/com/example/neticket/reservation/repository/ReservationRepository.java
- src/main/java/com/example/neticket/reservation/service/ReservationService.java
LeftSeats Refresh 기능 추가
캐시 생성, 캐시 삭제시 기존 캐시값이 존재 할때 예외 처리
거기에 따른 예외 type 새로 생성
Related to: #64
> Feat : LeftSeats Refresh 기능 추가

- src/main/java/com/example/neticket/reservation/repository/RedisRepository.java
- src/main/resources/static/js/basic.js
- src/main/resources/templates/addevent.html
프론트 관리자 페이지에 캐시 리스트 구현
갱신과 삭제버튼 구현
Related to: #64
> Feat: 프론트 관리자페이지에 갱신과 list 반영

- src/main/java/com/example/neticket/reservation/repository/RedisRepository.java
- src/main/java/com/example/neticket/reservation/service/ReservationService.java
RedisRepository에서 Lua 스크립트 작성해서 쿼리 날리는 방식으로 로직 변경
Related to: #70
> Fix : 캐시 사용시 남은 좌석 수 음수 문제 해결

- src/main/java/com/example/neticket/config/ResponseTimeAop.java
- src/main/java/com/example/neticket/reservation/controller/ReservationController.java
- src/main/java/com/example/neticket/reservation/service/ReservationService.java
- src/main/java/com/example/neticket/user/controller/AdminController.java
- src/main/java/com/example/neticket/user/service/AdminService.java
- src/main/resources/static/js/basic.js
- src/main/resources/templates/completed.html
AOP로 admin 유저 웹브라우저로 접속시 
예매하기 post 요청 할 때 서버 응답시간 나오게 구현
> dev <- Feature/redis lock

- src/main/java/com/example/neticket/event/dto/DetailEventResponseDto.java
- src/main/java/com/example/neticket/event/dto/TicketInfoResponseDto.java
- src/main/java/com/example/neticket/event/service/EventService.java
- src/main/java/com/example/neticket/reservation/service/ReservationService.java
DetailEventResponseDto.java
Resolved : # 75
> Refactor : DetailEventResponseDto에 필요없는Lombok 어노테이션 제거

- src/main/java/com/example/neticket/event/repository/TicketInfoRepository.java
- src/main/java/com/example/neticket/event/service/TicketInfoService.java
- src/main/java/com/example/neticket/reservation/repository/RedisRepository.java
- src/main/java/com/example/neticket/user/controller/AdminController.java
- src/main/java/com/example/neticket/user/service/AdminService.java
- src/main/resources/import.sql
- src/main/resources/static/js/basic.js
- src/main/resources/templates/addevent.html
admin이 서버 시작할때 오늘 날짜에 맞춰 isAvailable 재설정하는 reset 로직 구현
위의 reset버튼 프론트 admin 페이지에도 구현
TicketInfoService에서 스케쥴러가 사용할 db 쿼리 구현
redisRepository 에서 메서드 예외처리 수정
Resolves : #80
> Dev <- Fix/jang cache

- src/main/java/com/example/neticket/config/RedisConfig.java
- src/main/java/com/example/neticket/jwt/JwtUtil.java
- src/main/java/com/example/neticket/security/UserDetailsServiceImpl.java
> Feat : UserDetailsImpl 수정

- src/main/java/com/example/neticket/event/entity/Event.java
- src/main/java/com/example/neticket/event/entity/TicketInfo.java
ticketInfo Event 양방향 매핑 설정
Related to: #15
> Fix : 양방향 매핑 설정

- build.gradle
- src/main/java/com/example/neticket/config/RedisConfig.java
- src/main/java/com/example/neticket/event/repository/TicketInfoRepository.java
- src/main/java/com/example/neticket/event/service/TicketInfoService.java
- src/main/java/com/example/neticket/reservation/repository/ReservationRepository.java
- src/main/java/com/example/neticket/reservation/service/ReservationService.java
- src/main/java/com/example/neticket/security/UserDetailsServiceImpl.java
> Dev <- Feature/gy

- .github/workflows/gradle.yml
- src/main/java/com/example/neticket/security/UserDetailsServiceImpl.java
> Fix : docker build arm64 변경

- src/main/java/com/example/neticket/reservation/service/ReservationService.java
- src/test/java/com/example/neticket/reservation/service/ReservationServiceTest.java
> Fix : 예매하기 로직 롤백

- src/main/java/com/example/neticket/config/CacheConfig.java
- src/main/java/com/example/neticket/reservation/service/ReservationService.java
- src/test/java/com/example/neticket/reservation/service/ReservationServiceTest.java
> Fix : 캐시 타임아웃 조정, 서비스 로직 변경분으로 수정

- src/main/java/com/example/neticket/event/service/TicketInfoService.java
- src/main/java/com/example/neticket/reservation/repository/RedisRepository.java
자정 -> 1am으로 수정
refresh에서 쿼리 결과가 null일 시 예외처리를 0으로 수정
Related to: #122
> Fix : 티켓 예매 종료 오류 수정
